### ISSUE TITLE
Keep-Alive Stops

### ISSUE THREAD

**Issue by akutta** [emqx/emqtt#29]
I have not fully investigated this issue yet, but I can post logs if you like.  

Here are the conditions so far:
- default KeepAlive=90
- using ssl connections on port 8883

On initial connect, there is a proper:
 44 [debug] [listener-YmqGbHeKno@10.0.2.15:47297] SENT: PINGREQ(Q0, R0, D0)
 45 [debug] [listener-YmqGbHeKno@10.0.2.15:47297] SENT: <<192,0>>
[debug] [Client <0.3009.0>] RECV: PINGRESP(Q0, R0, D0)

This particular process is only doing subscriptions.  There are no publishes occurring from this.  After this initial KeepAlive, a topic is subscribed @ ~3:15:30 and SUBACK received shortly after.

 88 [debug] [Client <0.3009.0>] RECV: SUBACK(Q0, R0, D0, PacketId=2, QosTable=[1])
 89 03:16:00.769 [notice] <<...
 90 03:16:00.770 [notice] <<...
 91 03:16:00.771 [info] Write Event for: <<"topic">>
 92 03:16:00.771 [info] Publishing <<"...
 93 03:16:31.763 [notice] <<...
 94 03:16:31.763 [notice] <<...
 95 03:17:03.100 [notice] <<...
 96 03:17:03.101 [notice] <<...
 97 03:17:34.087 [notice] <<...
 98 03:17:34.087 [notice] <<...
 99 [warning] [Client <0.3009.0>] Connection lost for: ssl_closed  
100 [info] [Client <0.3009.0>] try reconnecting...
101 03:17:45.489 [info] {mqttc,<0.3009.0>,disconnected}
102 [info] [Client <0.3009.0>]: connecting to ...

The issue, is that there are no further KeepAlive's triggered.  And since we are relying on the internal reconnect process at this point, the KeepAlive process does not appear to be restarted. 

I have about a 30-40% chance per run to get it into this state.  If it gets into this state, it never leaves.

**Comment by erylee** [comment]
@akutta ssl options? could you send me the whole logs? email: feng at emqtt.io

**Comment by akutta** [comment]
@erylee 

I have just e-mailed it to you.

**Comment by akutta** [comment]
@erylee One additional note.  The server I am connecting to will disconnect the user if a keepalive is not received within 150% of the time specified.  Example:  KeepAlive = 90.  If a message hasn't been received within 135 seconds then the socket is disconnected.

**Comment by akutta** [comment]
I think I know what the issue is.

This client nearly guarantees that there will be a keep alive sent within 2x the keep-alive, while the server expects to have the keep-alive within 150% of the timing.  The keep-alive mechanism checks to see if there has been data sent to the server through the connected socket.  In order to have the server disconnect me, I need to send a subscribe message within the first 45 seconds (assuming 90 second keep-alive) of the last keep-alive.  

The keep-alive mechanism does not appear to re-enable properly after a disconnect / reconnect.

**Comment by heri16** [comment]
I was able to reproduce this with the AWS IoT servers. Rather nasty bug I must say.

**Comment by pulzzejason** [comment]
I have encountered this problem as well and debugged it further.  I know exactly what the problem is.

The emqttc_keepalive is recording the size of the last sent packet when it goes to "sleep" and then comparing it against the last sent packet when it "wakes up".  If they are not the same, it goes to "sleep" for another full keepalive duration.

The problem with this is that if your last message occurred immediately after your last keepalive, you can "sleep" for up to 2x the keepalive time.  This is exactly what Akutta was talking about.

You can either remove this check entirely and simply do a keepalive at the keep alive interval or the keepalive needs to know WHEN the last message was sent and determine the time from there.  Otherwise it is essentially guessing when the keep alive is suppose to be and it doesn't always work.

**Comment by sashaafm** [comment]
Bump

**Comment by gilbertwong96** [comment]
We have released the latest emqx now and the implementation is totally different from which is the past. Please try it.
